import {test,expect} from '@playwright/test';
import {components} from '../../content/catalog.mjs';
import {samples} from '../../content/samples.mjs';
async function ready(page){await expect(page.locator('.pg-status')).toHaveAttribute('data-state','ready',{timeout:65000});}
async function open(page,id){await page.goto('components/'+id+'/playground/');await ready(page);return page.frameLocator('wc-playground iframe');}
for(const c of components){test(`${c.name}: every published-package preset initializes`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page,c.id);for(let i=1;i<samples[c.id].length;i++){await page.locator('[data-preset]').selectOption(String(i));await ready(page);}expect(errors).toEqual([]);expect(await page.locator('.pg-log[data-level=error]').count()).toBe(0);});}
test('catalog, search and package-manager commands work',async({page})=>{await page.goto('');await expect(page.locator('[data-card]:visible')).toHaveCount(11);await page.locator('[data-category-filter="Graphics"]').click();await expect(page.locator('[data-card]:visible')).toHaveCount(3);await page.locator('[data-category-filter="All components"]').click();await page.getByLabel('Filter component catalog').fill('ribbon');await expect(page.locator('[data-card]:visible')).toHaveCount(1);await page.keyboard.press('Control+k');await page.getByLabel('Search site',{exact:true}).fill('spatial');await expect(page.locator('.search-item').first()).toContainText('RBushWeb');await page.keyboard.press('Escape');await page.goto('components/dockyard/installation/');await page.locator('[data-pm="pnpm"]').click();await expect(page.locator('[data-install]')).toContainText('pnpm add @wieslawsoltes/dockyard@0.2.0');});
test('mobile navigation and layout remain usable',async({page})=>{await page.setViewportSize({width:390,height:844});for(const route of ['','components/','guides/','components/drawingweb/','components/gridweb/installation/','playgrounds/']){await page.goto(route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' horizontal overflow').toBeTruthy();}await page.goto('');await page.getByLabel('Toggle navigation').click();await expect(page.locator('.main-nav')).toBeVisible();await page.locator('.main-nav').getByRole('link',{name:'Guides',exact:true}).click();await expect(page).toHaveTitle(/Guides/);await page.getByLabel('Switch color theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');});
test('static documentation works without JavaScript',async({browser})=>{const context=await browser.newContext({javaScriptEnabled:false});const page=await context.newPage();await page.goto(new URL('components/rbushweb/usage/',process.env.TEST_BASE_URL||'http://127.0.0.1:4173/WebComponents/').href);await expect(page.locator('h1')).toContainText('Usage guide');await expect(page.locator('.prose')).toContainText('RBush');await context.close();});
test('reactive inputs and asynchronous command use the real view model',async({page})=>{const frame=await open(page,'reactiveweb');await frame.locator('#first').fill('Ada');await frame.locator('#last').fill('Lovelace');await expect(frame.locator('#name')).toHaveText('Ada Lovelace');await frame.locator('#save').click();await expect(frame.locator('#message')).toContainText('Ada Lovelace');});
test('spatial index responds to pointer and nearest-neighbor mode',async({page})=>{const frame=await open(page,'rbushweb');await frame.locator('#mode').selectOption('nearest');await frame.locator('#spatial').click({position:{x:160,y:160}});await expect(frame.locator('#result')).toContainText('20');});
test('grid cell edits recompute dependent formulas',async({page})=>{const frame=await open(page,'gridweb');await frame.locator('#inspect').click();await expect(page.locator('.pg-console-output')).toContainText('8900');await frame.locator('#increase').click();await frame.locator('#inspect').click();await expect(page.locator('.pg-console-output')).toContainText('9260');});
test('ribbon commands change the application document',async({page})=>{const frame=await open(page,'ribbonweb');await frame.getByRole('button',{name:'Bold',exact:true}).click();await expect(frame.locator('#heading')).toHaveCSS('font-weight','700');});
test('docking retains editor text through float and dock',async({page})=>{const frame=await open(page,'dockyard');await frame.getByLabel('Workspace notes').fill('State survives a move.');await frame.locator('#float').click();await frame.locator('#dock').click();await expect(frame.getByLabel('Workspace notes')).toHaveValue('State survives a move.');});
test('drawing adds a real model object with undo',async({page})=>{const frame=await open(page,'drawingweb');await frame.locator('#add').click();await frame.locator('#undo').click();await expect(page.locator('.pg-console-output')).toContainText('Revision');});
test('draft restore is explicit and no shared code runs automatically',async({page})=>{await open(page,'reactiveweb');await page.locator('.pg-draft-menu summary').click();await page.locator('[data-save-draft]').click();await page.locator('.pg-draft-menu summary').click();await page.locator('[data-restore-draft]').click();await expect(page.locator('wc-playground iframe')).toHaveCount(0);await expect(page.locator('.pg-shared-notice')).toContainText('Review');await page.locator('[data-run]').click();await ready(page);const payload=await page.evaluate(async()=>{const m=await import(document.body.dataset.base+'assets/playground.js');return m.encodeShare({v:1,component:'reactiveweb',source:{js:"document.body.textContent='SHARED CODE RAN'",html:'<div>Review me</div>',css:''}})});await page.goto('components/reactiveweb/playground/#code='+payload);await expect(page.locator('.pg-shared-notice')).toContainText('Shared code loaded');await expect(page.locator('wc-playground iframe')).toHaveCount(0);await page.locator('[data-run]').click();await ready(page);await expect(page.frameLocator('iframe').locator('body')).toContainText('SHARED CODE RAN');});
test('sandbox denies site storage and parent document access',async({page})=>{await open(page,'rbushweb');const flags=await page.locator('iframe').getAttribute('sandbox');expect(flags).not.toContain('allow-same-origin');const child=page.frames().find(f=>f!==page.mainFrame());const access=await child.evaluate(()=>{let parent=false,storage=false;try{void window.parent.document;parent=true}catch{}try{void localStorage.length;storage=true}catch{}return{parent,storage}});expect(access).toEqual({parent:false,storage:false});});
test('all route pages have a visible main heading',async({page})=>{for(const c of components)for(const suffix of ['','installation/','usage/']){await page.goto('components/'+c.id+'/'+suffix);await expect(page.locator('main h1')).toBeVisible();}});
