import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';
import {components,guides} from '../content/catalog.mjs';import {samples} from '../content/samples.mjs';
const base=process.env.SITE_BASE||'/WebComponents/';
async function walk(dir){const list=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory())list.push(...await walk(file));else list.push(file)}return list}
test('eleven distinct component definitions and executable presets',()=>{assert.equal(components.length,11);assert.equal(new Set(components.map(c=>c.id)).size,11);for(const c of components){assert.ok(samples[c.id].length>=2,c.id);for(const s of samples[c.id]){assert.ok(s.js.includes(c.package),c.id+' uses real npm package');assert.ok(s.html);assert.ok(s.css)}}});
test('all four component routes have static titles, canonical links and correct accents',async()=>{for(const c of components)for(const tab of ['','playground/','installation/','usage/']){const html=await fs.readFile('dist/components/'+c.id+'/'+tab+'index.html','utf8');assert.match(html,/<h1[ >]/);assert.ok(html.includes(c.name));assert.ok(html.includes('style="--accent:'+c.color));assert.ok(html.includes('https://wieslawsoltes.github.io'+base+'components/'+c.id+'/'+tab));}});
test('every internal static link resolves inside the distribution',async()=>{const files=(await walk('dist')).filter(f=>f.endsWith('.html'));let checked=0;for(const file of files){const html=await fs.readFile(file,'utf8');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const href=match[1];if(!href.startsWith(base))continue;const clean=decodeURIComponent(href.split(/[?#]/)[0].slice(base.length));const target=path.join('dist',clean+(clean.endsWith('/')?'index.html':''));assert.ok(await fs.stat(target).catch(()=>null),`${file}: ${href}`);checked++}}assert.ok(checked>500);});
test('shared guides, search, runtime map, native assets, and metadata are emitted',async()=>{for(const g of guides)assert.ok(await fs.stat('dist/guides/'+g.id+'/index.html'));const manifest=JSON.parse(await fs.readFile('dist/runtime-manifest.json'));assert.equal(manifest.base,base);for(const href of [...Object.values(manifest.imports),...manifest.styles])assert.ok(await fs.stat('dist/'+href.slice(base.length)));assert.ok(await fs.stat('dist/skia/canvaskit.wasm'));assert.ok(await fs.stat('dist/skia/THIRD_PARTY_NOTICES.txt'));const index=JSON.parse(await fs.readFile('dist/search-index.json'));assert.equal(index.length,50);const info=JSON.parse(await fs.readFile('dist/build-info.json'));assert.equal(info.routes,57);});
test('no runtime font files or remote analytics are shipped',async()=>{const files=await walk('dist');assert.equal(files.filter(f=>/\.(ttf|otf|woff2?)$/i.test(f)).length,0);const html=await fs.readFile('dist/index.html','utf8');assert.ok(!html.includes('fonts.googleapis'));assert.ok(!html.includes('analytics'));assert.ok(!html.includes('assets/playground.js'));});
test('license and version boundaries are explicit',async()=>{const graph=components.find(c=>c.id==='quikgraphweb');assert.equal(graph.license,'MS-PL');const pkg=JSON.parse(await fs.readFile('package.json'));const lock=JSON.parse(await fs.readFile('package-lock.json'));assert.deepEqual(pkg.dependencies,lock.packages[''].dependencies);for(const c of components)assert.match(pkg.dependencies[c.package],/^\d+\.\d+\.\d+/);});
test('sandbox implementation omits same-origin privilege and validates message source',async()=>{const text=await fs.readFile('src/playground.mjs','utf8');assert.ok(text.includes("'allow-scripts allow-downloads'"));assert.ok(!text.includes('allow-same-origin'));assert.ok(text.includes("e.source!==this.frame?.contentWindow"));assert.ok(text.includes('m.runId!==this.runId'));assert.ok(text.includes('Shared code loaded for review'));});
